[package]
name = "oxcomm"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.9", features = ["blocking"] }
scraper = "0.22.0"
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["full"] }
urlencoding = "2.1.3"
